# Makefile for Writing Make Files Example
 
# *****************************************************
# Variables to control Makefile operation
 
CC = g++
CFLAGS = -Wall -g
 
# ****************************************************
# Targets needed to bring the executable up to date
all: main
main: main.o intentRecognition.o 
    $(CC) $(CFLAGS) -o main main.o intentRecognition.o 
 
# The main.o target can be written more simply
 
main.o: main.cpp intentRecognition.h
    $(CC) $(CFLAGS) -c main.cpp
 
intentRecognition.o : intentRecognition.h
 
